/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 73980be6e50be9cbc1d9fbf7ef4b35bd)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DB?: D1Database;
	BROWSER?: BrowserRun;
	AI?: Ai;
	TURNSTILE_HOSTNAMES?: "rolepatch.com,www.rolepatch.com";
	NODE_ENV?: "production";
	BETTER_AUTH_URL?: "https://rolepatch.com";
	NEURON_BUDGET?: DurableObjectNamespace /* NeuronBudgetDO from free-ai-gateway */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface CacheEnv {
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
