import './globals.css';

import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { AuthProvider } from '@/components/auth-provider';
import { AnalyticsProvider } from '@/components/posthog-provider';
import { SaaSMakerFeedback } from '@/components/saasmaker-feedback';
import { SiteNav } from '@/components/site-nav';
import { VitalsReporter } from '@/components/VitalsReporter';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  // Mono is used in the LaTeX editor, not on the landing LCP path.
  // Skipping preload keeps the Geist sans (LCP) the only font early.
  preload: false,
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export const metadata: Metadata = {
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: '/apple-touch-icon.png',
  },

  title: {
    default: 'RolePatch — AI resume tailoring for job applications',
    template: '%s | RolePatch',
  },
  description:
    'Tailor your resume to any job description with AI. Job fit scoring, interview prep with STAR stories, ATS optimization, cover letters, and word-level diff view.',
  keywords: [
    'resume tailor',
    'AI resume',
    'ATS score',
    'resume diff',
    'job application',
    'cover letter generator',
    'resume keywords',
    'resume optimizer',
    'job fit score',
    'interview prep',
    'STAR stories',
  ],
  authors: [{ name: 'RolePatch' }],
  creator: 'RolePatch',
  metadataBase: new URL('https://rolepatch.com'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://rolepatch.com',
    siteName: 'RolePatch',
    title: 'RolePatch — AI resume tailoring for job applications',
    description:
      'Tailor your resume to any job description with AI. See exactly what changed word by word.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'RolePatch — See every change in your resume',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    site: '@sarthakcodes',
    creator: '@sarthakcodes',
    title: 'RolePatch — AI resume tailoring for job applications',
    description: 'Tailor your resume to any job description with AI. See exactly what changed.',
    images: ['/og-image.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // No site-wide canonical — it was inherited by every page (including /tools/*)
  // and de-indexed free tools. Homepage and routes set self-canonicals.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link
          rel="alternate"
          type="application/rss+xml"
          title="RolePatch Blog"
          href="/blog/rss.xml"
        />
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":"https://sarthakagrawal.dev/#person","name":"Sarthak Agrawal","jobTitle":"AI Infrastructure & Product Engineer","url":"https://sarthakagrawal.dev","image":"https://avatars.githubusercontent.com/u/43884471?v=4","sameAs":["https://sarthakagrawal.dev","https://www.linkedin.com/in/sarthakagrawal927","https://github.com/sarthakagrawal927","https://x.com/sarthakcodes","https://huggingface.co/sarthakagrawal927"],"knowsAbout":["AI infrastructure","Local-first software","Post-training language models","AI code review","Cloudflare Workers","TypeScript","Rust"],"affiliation":{"@type":"Organization","@id":"https://sassmaker.com/#app","name":"SaaS Maker","url":"https://sassmaker.com"}},{"@type":"WebSite","@id":"https://rolepatch.com/#app","name":"RolePatch","alternateName":["Role Patch","rolepatch.com"],"url":"https://rolepatch.com","description":"AI-powered resume tailoring. Score fit against a job description, rewrite bullets for the role, and prep interviews.","publisher":{"@id":"https://sarthakagrawal.dev/#person"},"sameAs":["https://github.com/Significant-Hobbies/rolepatch"]}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
        {/* Microsoft Clarity — session replay + heatmaps (additive; PostHog stays) */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/y6buz6rkot";y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,"clarity","script","y6buz6rkot");window.clarity("set","project_id","rolepatch");`,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AnalyticsProvider>
          <SaaSMakerFeedback />
          <AuthProvider>
            <SiteNav />
            {children}
            <footer className="border-t border-border/60 px-6 py-6 text-sm text-muted-foreground">
              <div className="mx-auto flex max-w-6xl items-center justify-between gap-4">
                <span>RolePatch</span>
                <a href="/proof" className="transition-colors hover:text-foreground">
                  TrueHire proof
                </a>
              </div>
            </footer>
          </AuthProvider>
          <VitalsReporter />
        </AnalyticsProvider>
      </body>
    </html>
  );
}
